Repository ezbuy/ezorm, pull requests merged in 2019-11, with the labels that each got.

#112 db: add exportable MaxSession
  db/mongo.go
  db/mongo_config.go
Labels: enhancement

#114 db/mongo: add mongo session refresher
  .circleci/config.yml
  db/mongo.go
  example/blog/blog_test.go
  example/blog/gen_mongo_config.go
  go.mod
  go.sum
  tpl/bindata.go
  tpl/mongo_config.gogo
Labels: fixed, production

#117 feat: add CountE method for return error by driver
  example/blog/blog_test.go
  example/blog/gen_Blog_mongo_orm.go
  tpl/bindata.go
  tpl/mongo_collection.gogo
Labels: bug, production
